version: "3.8"
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres_clinica
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_DB:${DB_NAME}
      - POSTGRES_PASSWORD:${DB_PASSWORD}
    networks:
      - backend
  node:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: node_clinica
    working_dir: /home/node/app
    command: yarn start
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:3000
    environment:
      - DB_HOST:postgres
      - DB_PORT:${DB_PORT}
      - DB_USER:${DB_USER}
      - DB_NAME:${DB_NAME}
      - DB_PASSWORD:${DB_PASSWORD}
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
    internal: true
