FROM node:20-alpine3.18
# RUN echo "deb http://ftp.de.debian.org/debian sid main" >> /etc/apt/sources.list \
#   && apt-get update -yq \
#   && apt-get remove libgcc1 -yq \
#   && apt-get upgrade libp11-kit0 gcc-8 libc-bin gnutls-bin systemd -yq \
#   && apt autoremove -yq

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.12.1/wait /wait
RUN chmod +x /wait
WORKDIR /home/node/app
COPY ./package.json ./yarn.* .
RUN yarn
