version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_basic_api
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
  integration:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: test_unit_basic_api
    working_dir: /home/node/app
    command: yarn test --watchAll
    volumes:
      - ./src:/home/node/app/src
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./__tests__:/home/node/app/__tests__
      - ./jest.config.unit.ts:/home/node/app/jest.config.unit.ts
    network_mode: none
  unit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: test_integration_basic_api
    working_dir: /home/node/app
    command: /test-entrypoint.sh
    volumes:
      - ./src:/home/node/app/src
      - ./test-entrypoint.sh:/test-entrypoint.sh
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./__tests__:/home/node/app/__tests__
      - ./jest.config.integration.ts:/home/node/app/jest.config.integration.ts
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:3000
    env_file:
      .env
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
