version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_basic_api
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node_basic_api
    working_dir: /home/node/app
    command: /node-entrypoint.sh
    volumes:
      - ./src:/home/node/app/src
      - ./node-entrypoint.sh:/node-entrypoint.sh
      - ./tsconfig.json:/home/node/app/tsconfig.json
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:3000
    env_file:
      .env
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
